# Generated by Django 3.1 on 2020-08-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Megasena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso', models.IntegerField()),
                ('data_sorteio', models.CharField(max_length=11)),
                ('dezena_1', models.IntegerField()),
                ('dezena_2', models.IntegerField()),
                ('dezena_3', models.IntegerField()),
                ('dezena_4', models.IntegerField()),
                ('dezena_5', models.IntegerField()),
                ('dezena_6', models.IntegerField()),
            ],
        ),
    ]
